# Generated by Django 3.0.8 on 2020-07-23 17:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('endereco', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('telefone', models.CharField(max_length=32)),
                ('CPF', models.CharField(max_length=11)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('status', models.CharField(choices=[('ativo', 'ATIVO'), ('inativo', 'INATIVO')], max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
