# Generated by Django 3.0.8 on 2020-07-23 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='date',
            new_name='data_nascimento',
        ),
    ]
